Initial implementation for WeekDataAccess. Initial implementation for…
CSC207-2022F-UofT/course-project-blue-guppies pull request #23
Opened 2022-11-14 17:03 UTC by DanielLivshits

… the Data Access versions of the entities.

2022-11-16 04:52 UTC, POPPININ requested changes
Please finish the WeekDataAccess class and add appropriate documentation to all classes proposed.

2022-11-16 08:54 UTC, Fard-Faru requested changes
Hi Daniel, I noticed you are missing Documentation and test cases.

2022-11-17 21:31 UTC, POPPININ approved these changes
Looks good.

2022-11-17 22:03 UTC, Fard-Faru commented on src/test/java/data_access/DataAccessTaskTest.java
> +        DataAccessTask sleep = new DataAccessTask("get some sleep");
We all need some haha

2022-11-17 22:04 UTC, Fard-Faru approved these changes
Looks, Good Daniel!

2022-11-18 03:38 UTC, scissorkhizer approved these changes
Thank you for setting up the initial implementation for the WeekDataAccess and the corresponding classes. The tests have good breadth and depth based on the implementation thus far!

2022-11-18 03:42 UTC, merged